// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
// RUN: %cheri_cc1 %s -emit-llvm -o - -verify=atomics | %cheri_FileCheck %s -check-prefixes CHECK,HYBRID
// RUN: %riscv64_cheri_cc1 %s -target-feature +a -emit-llvm -o - -verify=atomics | FileCheck %s -check-prefixes CHECK,HYBRID
// RUN: %cheri_purecap_cc1 %s -emit-llvm -o - -verify=atomics | %cheri_FileCheck %s -check-prefixes CHECK,PURECAP
// RUN: %riscv64_cheri_purecap_cc1 -target-feature +a %s -emit-llvm -o - -verify=atomics | FileCheck %s -check-prefixes CHECK,PURECAP

// RUN: %riscv64_cheri_cc1 %s -emit-llvm -o - -verify=libcalls | FileCheck %s -check-prefixes CHECK,HYBRID-LIBCALLS
// RUN: %riscv64_cheri_purecap_cc1 %s -emit-llvm -o - -verify=libcalls | FileCheck %s -check-prefixes CHECK,PURECAP-LIBCALLS

// We used to require libcalls for CHERI cap atomics. Check that we don't any
// more for architectures with atomics support.

// atomics-no-diagnostics

// HYBRID-LABEL: define dso_local void @func1(
// HYBRID-SAME: ptr noundef [[P:%.*]]) #[[ATTR0:[0-9]+]] {
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// HYBRID-NEXT:    [[RES:%.*]] = alloca ptr, align 8
// HYBRID-NEXT:    [[RES2:%.*]] = alloca ptr, align 8
// HYBRID-NEXT:    [[CMPXCHG_BOOL:%.*]] = alloca i8, align 1
// HYBRID-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// HYBRID-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-NEXT:    [[TMP1:%.*]] = load atomic i64, ptr [[TMP0]] seq_cst, align 8
// HYBRID-NEXT:    store i64 [[TMP1]], ptr [[RES]], align 8
// HYBRID-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-NEXT:    [[TMP3:%.*]] = load i64, ptr [[RES]], align 8
// HYBRID-NEXT:    store atomic i64 [[TMP3]], ptr [[TMP2]] seq_cst, align 8
// HYBRID-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-NEXT:    [[TMP5:%.*]] = load i64, ptr [[RES]], align 8
// HYBRID-NEXT:    [[TMP6:%.*]] = atomicrmw xchg ptr [[TMP4]], i64 [[TMP5]] seq_cst, align 8
// HYBRID-NEXT:    store i64 [[TMP6]], ptr [[RES2]], align 8
// HYBRID-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-NEXT:    [[TMP8:%.*]] = load i64, ptr [[RES]], align 8
// HYBRID-NEXT:    [[TMP9:%.*]] = load i64, ptr [[RES2]], align 8
// HYBRID-NEXT:    [[TMP10:%.*]] = cmpxchg ptr [[TMP7]], i64 [[TMP8]], i64 [[TMP9]] seq_cst seq_cst, align 8
// HYBRID-NEXT:    [[TMP11:%.*]] = extractvalue { i64, i1 } [[TMP10]], 0
// HYBRID-NEXT:    [[TMP12:%.*]] = extractvalue { i64, i1 } [[TMP10]], 1
// HYBRID-NEXT:    br i1 [[TMP12]], label [[CMPXCHG_CONTINUE:%.*]], label [[CMPXCHG_STORE_EXPECTED:%.*]]
// HYBRID:       cmpxchg.store_expected:
// HYBRID-NEXT:    store i64 [[TMP11]], ptr [[RES]], align 8
// HYBRID-NEXT:    br label [[CMPXCHG_CONTINUE]]
// HYBRID:       cmpxchg.continue:
// HYBRID-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP12]] to i8
// HYBRID-NEXT:    store i8 [[FROMBOOL]], ptr [[CMPXCHG_BOOL]], align 1
// HYBRID-NEXT:    [[TMP13:%.*]] = load i8, ptr [[CMPXCHG_BOOL]], align 1
// HYBRID-NEXT:    [[TOBOOL:%.*]] = trunc i8 [[TMP13]] to i1
// HYBRID-NEXT:    ret void
//
// PURECAP-LABEL: define dso_local void @func1(
// PURECAP-SAME: ptr addrspace(200) noundef [[P:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[P_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-NEXT:    [[RES:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-NEXT:    [[RES2:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-NEXT:    [[CMPXCHG_BOOL:%.*]] = alloca i8, align 1, addrspace(200)
// PURECAP-NEXT:    store ptr addrspace(200) [[P]], ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-NEXT:    [[TMP1:%.*]] = load atomic ptr addrspace(200), ptr addrspace(200) [[TMP0]] seq_cst, align 16
// PURECAP-NEXT:    store ptr addrspace(200) [[TMP1]], ptr addrspace(200) [[RES]], align 16
// PURECAP-NEXT:    [[TMP2:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-NEXT:    [[TMP3:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES]], align 16
// PURECAP-NEXT:    store atomic ptr addrspace(200) [[TMP3]], ptr addrspace(200) [[TMP2]] seq_cst, align 16
// PURECAP-NEXT:    [[TMP4:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-NEXT:    [[TMP5:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES]], align 16
// PURECAP-NEXT:    [[TMP6:%.*]] = atomicrmw xchg ptr addrspace(200) [[TMP4]], ptr addrspace(200) [[TMP5]] seq_cst, align 16
// PURECAP-NEXT:    store ptr addrspace(200) [[TMP6]], ptr addrspace(200) [[RES2]], align 16
// PURECAP-NEXT:    [[TMP7:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-NEXT:    [[TMP8:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES]], align 16
// PURECAP-NEXT:    [[TMP9:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES2]], align 16
// PURECAP-NEXT:    [[TMP10:%.*]] = cmpxchg ptr addrspace(200) [[TMP7]], ptr addrspace(200) [[TMP8]], ptr addrspace(200) [[TMP9]] seq_cst seq_cst, align 16
// PURECAP-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP10]], 0
// PURECAP-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP10]], 1
// PURECAP-NEXT:    br i1 [[TMP12]], label [[CMPXCHG_CONTINUE:%.*]], label [[CMPXCHG_STORE_EXPECTED:%.*]]
// PURECAP:       cmpxchg.store_expected:
// PURECAP-NEXT:    store ptr addrspace(200) [[TMP11]], ptr addrspace(200) [[RES]], align 16
// PURECAP-NEXT:    br label [[CMPXCHG_CONTINUE]]
// PURECAP:       cmpxchg.continue:
// PURECAP-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP12]] to i8
// PURECAP-NEXT:    store i8 [[FROMBOOL]], ptr addrspace(200) [[CMPXCHG_BOOL]], align 1
// PURECAP-NEXT:    [[TMP13:%.*]] = load i8, ptr addrspace(200) [[CMPXCHG_BOOL]], align 1
// PURECAP-NEXT:    [[TOBOOL:%.*]] = trunc i8 [[TMP13]] to i1
// PURECAP-NEXT:    ret void
//
// HYBRID-LIBCALLS-LABEL: define dso_local void @func1(
// HYBRID-LIBCALLS-SAME: ptr noundef [[P:%.*]]) #[[ATTR0:[0-9]+]] {
// HYBRID-LIBCALLS-NEXT:  entry:
// HYBRID-LIBCALLS-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// HYBRID-LIBCALLS-NEXT:    [[RES:%.*]] = alloca ptr, align 8
// HYBRID-LIBCALLS-NEXT:    [[RES2:%.*]] = alloca ptr, align 8
// HYBRID-LIBCALLS-NEXT:    [[CMPXCHG_BOOL:%.*]] = alloca i8, align 1
// HYBRID-LIBCALLS-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP1:%.*]] = load atomic i64, ptr [[TMP0]] seq_cst, align 8
// HYBRID-LIBCALLS-NEXT:    store i64 [[TMP1]], ptr [[RES]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP3:%.*]] = load i64, ptr [[RES]], align 8
// HYBRID-LIBCALLS-NEXT:    store atomic i64 [[TMP3]], ptr [[TMP2]] seq_cst, align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP5:%.*]] = load i64, ptr [[RES]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP6:%.*]] = atomicrmw xchg ptr [[TMP4]], i64 [[TMP5]] seq_cst, align 8
// HYBRID-LIBCALLS-NEXT:    store i64 [[TMP6]], ptr [[RES2]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP8:%.*]] = load i64, ptr [[RES]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP9:%.*]] = load i64, ptr [[RES2]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP10:%.*]] = cmpxchg ptr [[TMP7]], i64 [[TMP8]], i64 [[TMP9]] seq_cst seq_cst, align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP11:%.*]] = extractvalue { i64, i1 } [[TMP10]], 0
// HYBRID-LIBCALLS-NEXT:    [[TMP12:%.*]] = extractvalue { i64, i1 } [[TMP10]], 1
// HYBRID-LIBCALLS-NEXT:    br i1 [[TMP12]], label [[CMPXCHG_CONTINUE:%.*]], label [[CMPXCHG_STORE_EXPECTED:%.*]]
// HYBRID-LIBCALLS:       cmpxchg.store_expected:
// HYBRID-LIBCALLS-NEXT:    store i64 [[TMP11]], ptr [[RES]], align 8
// HYBRID-LIBCALLS-NEXT:    br label [[CMPXCHG_CONTINUE]]
// HYBRID-LIBCALLS:       cmpxchg.continue:
// HYBRID-LIBCALLS-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP12]] to i8
// HYBRID-LIBCALLS-NEXT:    store i8 [[FROMBOOL]], ptr [[CMPXCHG_BOOL]], align 1
// HYBRID-LIBCALLS-NEXT:    [[TMP13:%.*]] = load i8, ptr [[CMPXCHG_BOOL]], align 1
// HYBRID-LIBCALLS-NEXT:    [[TOBOOL:%.*]] = trunc i8 [[TMP13]] to i1
// HYBRID-LIBCALLS-NEXT:    ret void
//
// PURECAP-LIBCALLS-LABEL: define dso_local void @func1(
// PURECAP-LIBCALLS-SAME: ptr addrspace(200) noundef [[P:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
// PURECAP-LIBCALLS-NEXT:  entry:
// PURECAP-LIBCALLS-NEXT:    [[P_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-LIBCALLS-NEXT:    [[RES:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-LIBCALLS-NEXT:    [[RES2:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-LIBCALLS-NEXT:    [[CMPXCHG_BOOL:%.*]] = alloca i8, align 1, addrspace(200)
// PURECAP-LIBCALLS-NEXT:    store ptr addrspace(200) [[P]], ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP1:%.*]] = load atomic ptr addrspace(200), ptr addrspace(200) [[TMP0]] seq_cst, align 16
// PURECAP-LIBCALLS-NEXT:    store ptr addrspace(200) [[TMP1]], ptr addrspace(200) [[RES]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP2:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP3:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES]], align 16
// PURECAP-LIBCALLS-NEXT:    store atomic ptr addrspace(200) [[TMP3]], ptr addrspace(200) [[TMP2]] seq_cst, align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP4:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP5:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP6:%.*]] = atomicrmw xchg ptr addrspace(200) [[TMP4]], ptr addrspace(200) [[TMP5]] seq_cst, align 16
// PURECAP-LIBCALLS-NEXT:    store ptr addrspace(200) [[TMP6]], ptr addrspace(200) [[RES2]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP7:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP8:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP9:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES2]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP10:%.*]] = cmpxchg ptr addrspace(200) [[TMP7]], ptr addrspace(200) [[TMP8]], ptr addrspace(200) [[TMP9]] seq_cst seq_cst, align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP10]], 0
// PURECAP-LIBCALLS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP10]], 1
// PURECAP-LIBCALLS-NEXT:    br i1 [[TMP12]], label [[CMPXCHG_CONTINUE:%.*]], label [[CMPXCHG_STORE_EXPECTED:%.*]]
// PURECAP-LIBCALLS:       cmpxchg.store_expected:
// PURECAP-LIBCALLS-NEXT:    store ptr addrspace(200) [[TMP11]], ptr addrspace(200) [[RES]], align 16
// PURECAP-LIBCALLS-NEXT:    br label [[CMPXCHG_CONTINUE]]
// PURECAP-LIBCALLS:       cmpxchg.continue:
// PURECAP-LIBCALLS-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP12]] to i8
// PURECAP-LIBCALLS-NEXT:    store i8 [[FROMBOOL]], ptr addrspace(200) [[CMPXCHG_BOOL]], align 1
// PURECAP-LIBCALLS-NEXT:    [[TMP13:%.*]] = load i8, ptr addrspace(200) [[CMPXCHG_BOOL]], align 1
// PURECAP-LIBCALLS-NEXT:    [[TOBOOL:%.*]] = trunc i8 [[TMP13]] to i1
// PURECAP-LIBCALLS-NEXT:    ret void
//
void func1(void **p) {
  void *res;
  void *res2;
  __atomic_load(p, &res, 5); // libcalls-warning{{large atomic operation may incur significant performance penalty}}
  __atomic_store(p, &res, 5); // libcalls-warning{{large atomic operation may incur significant performance penalty}}
  __atomic_exchange(p, &res, &res2, 5); // libcalls-warning{{large atomic operation may incur significant performance penalty}}
  __atomic_compare_exchange(p, &res, &res2, 0, 5, 5); // libcalls-warning{{large atomic operation may incur significant performance penalty}}




}

// HYBRID-LABEL: define dso_local void @func2(
// HYBRID-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// HYBRID-NEXT:    [[RES:%.*]] = alloca ptr addrspace(200), align 16
// HYBRID-NEXT:    [[RES2:%.*]] = alloca ptr addrspace(200), align 16
// HYBRID-NEXT:    [[CMPXCHG_BOOL:%.*]] = alloca i8, align 1
// HYBRID-NEXT:    [[DOTATOMICTMP:%.*]] = alloca i64, align 8
// HYBRID-NEXT:    [[ATOMIC_INTCAP_ARG:%.*]] = alloca ptr addrspace(200), align 16
// HYBRID-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca ptr addrspace(200), align 16
// HYBRID-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// HYBRID-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-NEXT:    [[TMP1:%.*]] = load atomic ptr addrspace(200), ptr [[TMP0]] seq_cst, align 16
// HYBRID-NEXT:    store ptr addrspace(200) [[TMP1]], ptr [[RES]], align 16
// HYBRID-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-NEXT:    [[TMP3:%.*]] = load ptr addrspace(200), ptr [[RES]], align 16
// HYBRID-NEXT:    store atomic ptr addrspace(200) [[TMP3]], ptr [[TMP2]] seq_cst, align 16
// HYBRID-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-NEXT:    [[TMP5:%.*]] = load ptr addrspace(200), ptr [[RES]], align 16
// HYBRID-NEXT:    [[TMP6:%.*]] = atomicrmw xchg ptr [[TMP4]], ptr addrspace(200) [[TMP5]] seq_cst, align 16
// HYBRID-NEXT:    store ptr addrspace(200) [[TMP6]], ptr [[RES2]], align 16
// HYBRID-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-NEXT:    [[TMP8:%.*]] = load ptr addrspace(200), ptr [[RES]], align 16
// HYBRID-NEXT:    [[TMP9:%.*]] = load ptr addrspace(200), ptr [[RES2]], align 16
// HYBRID-NEXT:    [[TMP10:%.*]] = cmpxchg ptr [[TMP7]], ptr addrspace(200) [[TMP8]], ptr addrspace(200) [[TMP9]] seq_cst seq_cst, align 16
// HYBRID-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP10]], 0
// HYBRID-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP10]], 1
// HYBRID-NEXT:    br i1 [[TMP12]], label [[CMPXCHG_CONTINUE:%.*]], label [[CMPXCHG_STORE_EXPECTED:%.*]]
// HYBRID:       cmpxchg.store_expected:
// HYBRID-NEXT:    store ptr addrspace(200) [[TMP11]], ptr [[RES]], align 16
// HYBRID-NEXT:    br label [[CMPXCHG_CONTINUE]]
// HYBRID:       cmpxchg.continue:
// HYBRID-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP12]] to i8
// HYBRID-NEXT:    store i8 [[FROMBOOL]], ptr [[CMPXCHG_BOOL]], align 1
// HYBRID-NEXT:    [[TMP13:%.*]] = load i8, ptr [[CMPXCHG_BOOL]], align 1
// HYBRID-NEXT:    [[TOBOOL:%.*]] = trunc i8 [[TMP13]] to i1
// HYBRID-NEXT:    [[TMP14:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-NEXT:    store i64 1, ptr [[DOTATOMICTMP]], align 8
// HYBRID-NEXT:    [[TMP15:%.*]] = load i64, ptr [[DOTATOMICTMP]], align 8
// HYBRID-NEXT:    [[TMP16:%.*]] = getelementptr i8, ptr addrspace(200) null, i64 [[TMP15]]
// HYBRID-NEXT:    store ptr addrspace(200) [[TMP16]], ptr [[ATOMIC_INTCAP_ARG]], align 16
// HYBRID-NEXT:    [[TMP17:%.*]] = load ptr addrspace(200), ptr [[ATOMIC_INTCAP_ARG]], align 16
// HYBRID-NEXT:    [[TMP18:%.*]] = atomicrmw add ptr [[TMP14]], ptr addrspace(200) [[TMP17]] seq_cst, align 16
// HYBRID-NEXT:    store ptr addrspace(200) [[TMP18]], ptr [[ATOMIC_TEMP]], align 16
// HYBRID-NEXT:    [[TMP19:%.*]] = load ptr addrspace(200), ptr [[ATOMIC_TEMP]], align 16
// HYBRID-NEXT:    ret void
//
// PURECAP-LABEL: define dso_local void @func2(
// PURECAP-SAME: ptr addrspace(200) noundef [[P:%.*]]) addrspace(200) #[[ATTR0]] {
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[P_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-NEXT:    [[RES:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-NEXT:    [[RES2:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-NEXT:    [[CMPXCHG_BOOL:%.*]] = alloca i8, align 1, addrspace(200)
// PURECAP-NEXT:    [[DOTATOMICTMP:%.*]] = alloca i64, align 8, addrspace(200)
// PURECAP-NEXT:    [[ATOMIC_INTCAP_ARG:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-NEXT:    store ptr addrspace(200) [[P]], ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-NEXT:    [[TMP1:%.*]] = load atomic ptr addrspace(200), ptr addrspace(200) [[TMP0]] seq_cst, align 16
// PURECAP-NEXT:    store ptr addrspace(200) [[TMP1]], ptr addrspace(200) [[RES]], align 16
// PURECAP-NEXT:    [[TMP2:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-NEXT:    [[TMP3:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES]], align 16
// PURECAP-NEXT:    store atomic ptr addrspace(200) [[TMP3]], ptr addrspace(200) [[TMP2]] seq_cst, align 16
// PURECAP-NEXT:    [[TMP4:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-NEXT:    [[TMP5:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES]], align 16
// PURECAP-NEXT:    [[TMP6:%.*]] = atomicrmw xchg ptr addrspace(200) [[TMP4]], ptr addrspace(200) [[TMP5]] seq_cst, align 16
// PURECAP-NEXT:    store ptr addrspace(200) [[TMP6]], ptr addrspace(200) [[RES2]], align 16
// PURECAP-NEXT:    [[TMP7:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-NEXT:    [[TMP8:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES]], align 16
// PURECAP-NEXT:    [[TMP9:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES2]], align 16
// PURECAP-NEXT:    [[TMP10:%.*]] = cmpxchg ptr addrspace(200) [[TMP7]], ptr addrspace(200) [[TMP8]], ptr addrspace(200) [[TMP9]] seq_cst seq_cst, align 16
// PURECAP-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP10]], 0
// PURECAP-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP10]], 1
// PURECAP-NEXT:    br i1 [[TMP12]], label [[CMPXCHG_CONTINUE:%.*]], label [[CMPXCHG_STORE_EXPECTED:%.*]]
// PURECAP:       cmpxchg.store_expected:
// PURECAP-NEXT:    store ptr addrspace(200) [[TMP11]], ptr addrspace(200) [[RES]], align 16
// PURECAP-NEXT:    br label [[CMPXCHG_CONTINUE]]
// PURECAP:       cmpxchg.continue:
// PURECAP-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP12]] to i8
// PURECAP-NEXT:    store i8 [[FROMBOOL]], ptr addrspace(200) [[CMPXCHG_BOOL]], align 1
// PURECAP-NEXT:    [[TMP13:%.*]] = load i8, ptr addrspace(200) [[CMPXCHG_BOOL]], align 1
// PURECAP-NEXT:    [[TOBOOL:%.*]] = trunc i8 [[TMP13]] to i1
// PURECAP-NEXT:    [[TMP14:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-NEXT:    store i64 1, ptr addrspace(200) [[DOTATOMICTMP]], align 8
// PURECAP-NEXT:    [[TMP15:%.*]] = load i64, ptr addrspace(200) [[DOTATOMICTMP]], align 8
// PURECAP-NEXT:    [[TMP16:%.*]] = getelementptr i8, ptr addrspace(200) null, i64 [[TMP15]]
// PURECAP-NEXT:    store ptr addrspace(200) [[TMP16]], ptr addrspace(200) [[ATOMIC_INTCAP_ARG]], align 16
// PURECAP-NEXT:    [[TMP17:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[ATOMIC_INTCAP_ARG]], align 16
// PURECAP-NEXT:    [[TMP18:%.*]] = atomicrmw add ptr addrspace(200) [[TMP14]], ptr addrspace(200) [[TMP17]] seq_cst, align 16
// PURECAP-NEXT:    store ptr addrspace(200) [[TMP18]], ptr addrspace(200) [[ATOMIC_TEMP]], align 16
// PURECAP-NEXT:    [[TMP19:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[ATOMIC_TEMP]], align 16
// PURECAP-NEXT:    ret void
//
// HYBRID-LIBCALLS-LABEL: define dso_local void @func2(
// HYBRID-LIBCALLS-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// HYBRID-LIBCALLS-NEXT:  entry:
// HYBRID-LIBCALLS-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// HYBRID-LIBCALLS-NEXT:    [[RES:%.*]] = alloca ptr addrspace(200), align 16
// HYBRID-LIBCALLS-NEXT:    [[RES2:%.*]] = alloca ptr addrspace(200), align 16
// HYBRID-LIBCALLS-NEXT:    [[CMPXCHG_BOOL:%.*]] = alloca i8, align 1
// HYBRID-LIBCALLS-NEXT:    [[DOTATOMICTMP:%.*]] = alloca i64, align 8
// HYBRID-LIBCALLS-NEXT:    [[ATOMIC_INTCAP_ARG:%.*]] = alloca ptr addrspace(200), align 16
// HYBRID-LIBCALLS-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca ptr addrspace(200), align 16
// HYBRID-LIBCALLS-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP1:%.*]] = load atomic ptr addrspace(200), ptr [[TMP0]] seq_cst, align 16
// HYBRID-LIBCALLS-NEXT:    store ptr addrspace(200) [[TMP1]], ptr [[RES]], align 16
// HYBRID-LIBCALLS-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP3:%.*]] = load ptr addrspace(200), ptr [[RES]], align 16
// HYBRID-LIBCALLS-NEXT:    store atomic ptr addrspace(200) [[TMP3]], ptr [[TMP2]] seq_cst, align 16
// HYBRID-LIBCALLS-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP5:%.*]] = load ptr addrspace(200), ptr [[RES]], align 16
// HYBRID-LIBCALLS-NEXT:    [[TMP6:%.*]] = atomicrmw xchg ptr [[TMP4]], ptr addrspace(200) [[TMP5]] seq_cst, align 16
// HYBRID-LIBCALLS-NEXT:    store ptr addrspace(200) [[TMP6]], ptr [[RES2]], align 16
// HYBRID-LIBCALLS-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP8:%.*]] = load ptr addrspace(200), ptr [[RES]], align 16
// HYBRID-LIBCALLS-NEXT:    [[TMP9:%.*]] = load ptr addrspace(200), ptr [[RES2]], align 16
// HYBRID-LIBCALLS-NEXT:    [[TMP10:%.*]] = cmpxchg ptr [[TMP7]], ptr addrspace(200) [[TMP8]], ptr addrspace(200) [[TMP9]] seq_cst seq_cst, align 16
// HYBRID-LIBCALLS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP10]], 0
// HYBRID-LIBCALLS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP10]], 1
// HYBRID-LIBCALLS-NEXT:    br i1 [[TMP12]], label [[CMPXCHG_CONTINUE:%.*]], label [[CMPXCHG_STORE_EXPECTED:%.*]]
// HYBRID-LIBCALLS:       cmpxchg.store_expected:
// HYBRID-LIBCALLS-NEXT:    store ptr addrspace(200) [[TMP11]], ptr [[RES]], align 16
// HYBRID-LIBCALLS-NEXT:    br label [[CMPXCHG_CONTINUE]]
// HYBRID-LIBCALLS:       cmpxchg.continue:
// HYBRID-LIBCALLS-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP12]] to i8
// HYBRID-LIBCALLS-NEXT:    store i8 [[FROMBOOL]], ptr [[CMPXCHG_BOOL]], align 1
// HYBRID-LIBCALLS-NEXT:    [[TMP13:%.*]] = load i8, ptr [[CMPXCHG_BOOL]], align 1
// HYBRID-LIBCALLS-NEXT:    [[TOBOOL:%.*]] = trunc i8 [[TMP13]] to i1
// HYBRID-LIBCALLS-NEXT:    [[TMP14:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-LIBCALLS-NEXT:    store i64 1, ptr [[DOTATOMICTMP]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP15:%.*]] = load i64, ptr [[DOTATOMICTMP]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP16:%.*]] = getelementptr i8, ptr addrspace(200) null, i64 [[TMP15]]
// HYBRID-LIBCALLS-NEXT:    store ptr addrspace(200) [[TMP16]], ptr [[ATOMIC_INTCAP_ARG]], align 16
// HYBRID-LIBCALLS-NEXT:    [[TMP17:%.*]] = load ptr addrspace(200), ptr [[ATOMIC_INTCAP_ARG]], align 16
// HYBRID-LIBCALLS-NEXT:    [[TMP18:%.*]] = atomicrmw add ptr [[TMP14]], ptr addrspace(200) [[TMP17]] seq_cst, align 16
// HYBRID-LIBCALLS-NEXT:    store ptr addrspace(200) [[TMP18]], ptr [[ATOMIC_TEMP]], align 16
// HYBRID-LIBCALLS-NEXT:    [[TMP19:%.*]] = load ptr addrspace(200), ptr [[ATOMIC_TEMP]], align 16
// HYBRID-LIBCALLS-NEXT:    ret void
//
// PURECAP-LIBCALLS-LABEL: define dso_local void @func2(
// PURECAP-LIBCALLS-SAME: ptr addrspace(200) noundef [[P:%.*]]) addrspace(200) #[[ATTR0]] {
// PURECAP-LIBCALLS-NEXT:  entry:
// PURECAP-LIBCALLS-NEXT:    [[P_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-LIBCALLS-NEXT:    [[RES:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-LIBCALLS-NEXT:    [[RES2:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-LIBCALLS-NEXT:    [[CMPXCHG_BOOL:%.*]] = alloca i8, align 1, addrspace(200)
// PURECAP-LIBCALLS-NEXT:    [[DOTATOMICTMP:%.*]] = alloca i64, align 8, addrspace(200)
// PURECAP-LIBCALLS-NEXT:    [[ATOMIC_INTCAP_ARG:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-LIBCALLS-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-LIBCALLS-NEXT:    store ptr addrspace(200) [[P]], ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP1:%.*]] = load atomic ptr addrspace(200), ptr addrspace(200) [[TMP0]] seq_cst, align 16
// PURECAP-LIBCALLS-NEXT:    store ptr addrspace(200) [[TMP1]], ptr addrspace(200) [[RES]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP2:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP3:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES]], align 16
// PURECAP-LIBCALLS-NEXT:    store atomic ptr addrspace(200) [[TMP3]], ptr addrspace(200) [[TMP2]] seq_cst, align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP4:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP5:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP6:%.*]] = atomicrmw xchg ptr addrspace(200) [[TMP4]], ptr addrspace(200) [[TMP5]] seq_cst, align 16
// PURECAP-LIBCALLS-NEXT:    store ptr addrspace(200) [[TMP6]], ptr addrspace(200) [[RES2]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP7:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP8:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP9:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES2]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP10:%.*]] = cmpxchg ptr addrspace(200) [[TMP7]], ptr addrspace(200) [[TMP8]], ptr addrspace(200) [[TMP9]] seq_cst seq_cst, align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP10]], 0
// PURECAP-LIBCALLS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP10]], 1
// PURECAP-LIBCALLS-NEXT:    br i1 [[TMP12]], label [[CMPXCHG_CONTINUE:%.*]], label [[CMPXCHG_STORE_EXPECTED:%.*]]
// PURECAP-LIBCALLS:       cmpxchg.store_expected:
// PURECAP-LIBCALLS-NEXT:    store ptr addrspace(200) [[TMP11]], ptr addrspace(200) [[RES]], align 16
// PURECAP-LIBCALLS-NEXT:    br label [[CMPXCHG_CONTINUE]]
// PURECAP-LIBCALLS:       cmpxchg.continue:
// PURECAP-LIBCALLS-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP12]] to i8
// PURECAP-LIBCALLS-NEXT:    store i8 [[FROMBOOL]], ptr addrspace(200) [[CMPXCHG_BOOL]], align 1
// PURECAP-LIBCALLS-NEXT:    [[TMP13:%.*]] = load i8, ptr addrspace(200) [[CMPXCHG_BOOL]], align 1
// PURECAP-LIBCALLS-NEXT:    [[TOBOOL:%.*]] = trunc i8 [[TMP13]] to i1
// PURECAP-LIBCALLS-NEXT:    [[TMP14:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-LIBCALLS-NEXT:    store i64 1, ptr addrspace(200) [[DOTATOMICTMP]], align 8
// PURECAP-LIBCALLS-NEXT:    [[TMP15:%.*]] = load i64, ptr addrspace(200) [[DOTATOMICTMP]], align 8
// PURECAP-LIBCALLS-NEXT:    [[TMP16:%.*]] = getelementptr i8, ptr addrspace(200) null, i64 [[TMP15]]
// PURECAP-LIBCALLS-NEXT:    store ptr addrspace(200) [[TMP16]], ptr addrspace(200) [[ATOMIC_INTCAP_ARG]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP17:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[ATOMIC_INTCAP_ARG]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP18:%.*]] = atomicrmw add ptr addrspace(200) [[TMP14]], ptr addrspace(200) [[TMP17]] seq_cst, align 16
// PURECAP-LIBCALLS-NEXT:    store ptr addrspace(200) [[TMP18]], ptr addrspace(200) [[ATOMIC_TEMP]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP19:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[ATOMIC_TEMP]], align 16
// PURECAP-LIBCALLS-NEXT:    ret void
//
void func2(int *__capability *p) {


  int *__capability res;
  int *__capability res2;
  __atomic_load(p, &res, __ATOMIC_SEQ_CST); // libcalls-warning{{large atomic operation may incur significant performance penalty}}
  __atomic_store(p, &res, __ATOMIC_SEQ_CST); // libcalls-warning{{large atomic operation may incur significant performance penalty}}
  __atomic_exchange(p, &res, &res2, __ATOMIC_SEQ_CST); // libcalls-warning{{large atomic operation may incur significant performance penalty}}
  __atomic_compare_exchange(p, &res, &res2, 0, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST); // libcalls-warning{{large atomic operation may incur significant performance penalty}}
  __atomic_fetch_add(p, 1, __ATOMIC_SEQ_CST); // libcalls-warning{{large atomic operation may incur significant performance penalty}}
}

// HYBRID-LABEL: define dso_local void @func3(
// HYBRID-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// HYBRID-NEXT:    [[RES:%.*]] = alloca ptr addrspace(200), align 16
// HYBRID-NEXT:    [[RES2:%.*]] = alloca ptr addrspace(200), align 16
// HYBRID-NEXT:    [[CMPXCHG_BOOL:%.*]] = alloca i8, align 1
// HYBRID-NEXT:    [[DOTATOMICTMP:%.*]] = alloca ptr addrspace(200), align 16
// HYBRID-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca ptr addrspace(200), align 16
// HYBRID-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// HYBRID-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-NEXT:    [[TMP1:%.*]] = load atomic ptr addrspace(200), ptr [[TMP0]] seq_cst, align 16
// HYBRID-NEXT:    store ptr addrspace(200) [[TMP1]], ptr [[RES]], align 16
// HYBRID-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-NEXT:    [[TMP3:%.*]] = load ptr addrspace(200), ptr [[RES]], align 16
// HYBRID-NEXT:    store atomic ptr addrspace(200) [[TMP3]], ptr [[TMP2]] seq_cst, align 16
// HYBRID-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-NEXT:    [[TMP5:%.*]] = load ptr addrspace(200), ptr [[RES]], align 16
// HYBRID-NEXT:    [[TMP6:%.*]] = atomicrmw xchg ptr [[TMP4]], ptr addrspace(200) [[TMP5]] seq_cst, align 16
// HYBRID-NEXT:    store ptr addrspace(200) [[TMP6]], ptr [[RES2]], align 16
// HYBRID-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-NEXT:    [[TMP8:%.*]] = load ptr addrspace(200), ptr [[RES]], align 16
// HYBRID-NEXT:    [[TMP9:%.*]] = load ptr addrspace(200), ptr [[RES2]], align 16
// HYBRID-NEXT:    [[TMP10:%.*]] = cmpxchg ptr [[TMP7]], ptr addrspace(200) [[TMP8]], ptr addrspace(200) [[TMP9]] seq_cst seq_cst, align 16
// HYBRID-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP10]], 0
// HYBRID-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP10]], 1
// HYBRID-NEXT:    br i1 [[TMP12]], label [[CMPXCHG_CONTINUE:%.*]], label [[CMPXCHG_STORE_EXPECTED:%.*]]
// HYBRID:       cmpxchg.store_expected:
// HYBRID-NEXT:    store ptr addrspace(200) [[TMP11]], ptr [[RES]], align 16
// HYBRID-NEXT:    br label [[CMPXCHG_CONTINUE]]
// HYBRID:       cmpxchg.continue:
// HYBRID-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP12]] to i8
// HYBRID-NEXT:    store i8 [[FROMBOOL]], ptr [[CMPXCHG_BOOL]], align 1
// HYBRID-NEXT:    [[TMP13:%.*]] = load i8, ptr [[CMPXCHG_BOOL]], align 1
// HYBRID-NEXT:    [[TOBOOL:%.*]] = trunc i8 [[TMP13]] to i1
// HYBRID-NEXT:    [[TMP14:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-NEXT:    store ptr addrspace(200) getelementptr (i8, ptr addrspace(200) null, i64 1), ptr [[DOTATOMICTMP]], align 16
// HYBRID-NEXT:    [[TMP15:%.*]] = load ptr addrspace(200), ptr [[DOTATOMICTMP]], align 16
// HYBRID-NEXT:    [[TMP16:%.*]] = atomicrmw add ptr [[TMP14]], ptr addrspace(200) [[TMP15]] seq_cst, align 16
// HYBRID-NEXT:    store ptr addrspace(200) [[TMP16]], ptr [[ATOMIC_TEMP]], align 16
// HYBRID-NEXT:    [[TMP17:%.*]] = load ptr addrspace(200), ptr [[ATOMIC_TEMP]], align 16
// HYBRID-NEXT:    ret void
//
// PURECAP-LABEL: define dso_local void @func3(
// PURECAP-SAME: ptr addrspace(200) noundef [[P:%.*]]) addrspace(200) #[[ATTR0]] {
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[P_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-NEXT:    [[RES:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-NEXT:    [[RES2:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-NEXT:    [[CMPXCHG_BOOL:%.*]] = alloca i8, align 1, addrspace(200)
// PURECAP-NEXT:    [[DOTATOMICTMP:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-NEXT:    store ptr addrspace(200) [[P]], ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-NEXT:    [[TMP1:%.*]] = load atomic ptr addrspace(200), ptr addrspace(200) [[TMP0]] seq_cst, align 16
// PURECAP-NEXT:    store ptr addrspace(200) [[TMP1]], ptr addrspace(200) [[RES]], align 16
// PURECAP-NEXT:    [[TMP2:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-NEXT:    [[TMP3:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES]], align 16
// PURECAP-NEXT:    store atomic ptr addrspace(200) [[TMP3]], ptr addrspace(200) [[TMP2]] seq_cst, align 16
// PURECAP-NEXT:    [[TMP4:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-NEXT:    [[TMP5:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES]], align 16
// PURECAP-NEXT:    [[TMP6:%.*]] = atomicrmw xchg ptr addrspace(200) [[TMP4]], ptr addrspace(200) [[TMP5]] seq_cst, align 16
// PURECAP-NEXT:    store ptr addrspace(200) [[TMP6]], ptr addrspace(200) [[RES2]], align 16
// PURECAP-NEXT:    [[TMP7:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-NEXT:    [[TMP8:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES]], align 16
// PURECAP-NEXT:    [[TMP9:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES2]], align 16
// PURECAP-NEXT:    [[TMP10:%.*]] = cmpxchg ptr addrspace(200) [[TMP7]], ptr addrspace(200) [[TMP8]], ptr addrspace(200) [[TMP9]] seq_cst seq_cst, align 16
// PURECAP-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP10]], 0
// PURECAP-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP10]], 1
// PURECAP-NEXT:    br i1 [[TMP12]], label [[CMPXCHG_CONTINUE:%.*]], label [[CMPXCHG_STORE_EXPECTED:%.*]]
// PURECAP:       cmpxchg.store_expected:
// PURECAP-NEXT:    store ptr addrspace(200) [[TMP11]], ptr addrspace(200) [[RES]], align 16
// PURECAP-NEXT:    br label [[CMPXCHG_CONTINUE]]
// PURECAP:       cmpxchg.continue:
// PURECAP-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP12]] to i8
// PURECAP-NEXT:    store i8 [[FROMBOOL]], ptr addrspace(200) [[CMPXCHG_BOOL]], align 1
// PURECAP-NEXT:    [[TMP13:%.*]] = load i8, ptr addrspace(200) [[CMPXCHG_BOOL]], align 1
// PURECAP-NEXT:    [[TOBOOL:%.*]] = trunc i8 [[TMP13]] to i1
// PURECAP-NEXT:    [[TMP14:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-NEXT:    store ptr addrspace(200) getelementptr (i8, ptr addrspace(200) null, i64 1), ptr addrspace(200) [[DOTATOMICTMP]], align 16
// PURECAP-NEXT:    [[TMP15:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[DOTATOMICTMP]], align 16
// PURECAP-NEXT:    [[TMP16:%.*]] = atomicrmw add ptr addrspace(200) [[TMP14]], ptr addrspace(200) [[TMP15]] seq_cst, align 16
// PURECAP-NEXT:    store ptr addrspace(200) [[TMP16]], ptr addrspace(200) [[ATOMIC_TEMP]], align 16
// PURECAP-NEXT:    [[TMP17:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[ATOMIC_TEMP]], align 16
// PURECAP-NEXT:    ret void
//
// HYBRID-LIBCALLS-LABEL: define dso_local void @func3(
// HYBRID-LIBCALLS-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// HYBRID-LIBCALLS-NEXT:  entry:
// HYBRID-LIBCALLS-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// HYBRID-LIBCALLS-NEXT:    [[RES:%.*]] = alloca ptr addrspace(200), align 16
// HYBRID-LIBCALLS-NEXT:    [[RES2:%.*]] = alloca ptr addrspace(200), align 16
// HYBRID-LIBCALLS-NEXT:    [[CMPXCHG_BOOL:%.*]] = alloca i8, align 1
// HYBRID-LIBCALLS-NEXT:    [[DOTATOMICTMP:%.*]] = alloca ptr addrspace(200), align 16
// HYBRID-LIBCALLS-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca ptr addrspace(200), align 16
// HYBRID-LIBCALLS-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP1:%.*]] = load atomic ptr addrspace(200), ptr [[TMP0]] seq_cst, align 16
// HYBRID-LIBCALLS-NEXT:    store ptr addrspace(200) [[TMP1]], ptr [[RES]], align 16
// HYBRID-LIBCALLS-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP3:%.*]] = load ptr addrspace(200), ptr [[RES]], align 16
// HYBRID-LIBCALLS-NEXT:    store atomic ptr addrspace(200) [[TMP3]], ptr [[TMP2]] seq_cst, align 16
// HYBRID-LIBCALLS-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP5:%.*]] = load ptr addrspace(200), ptr [[RES]], align 16
// HYBRID-LIBCALLS-NEXT:    [[TMP6:%.*]] = atomicrmw xchg ptr [[TMP4]], ptr addrspace(200) [[TMP5]] seq_cst, align 16
// HYBRID-LIBCALLS-NEXT:    store ptr addrspace(200) [[TMP6]], ptr [[RES2]], align 16
// HYBRID-LIBCALLS-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP8:%.*]] = load ptr addrspace(200), ptr [[RES]], align 16
// HYBRID-LIBCALLS-NEXT:    [[TMP9:%.*]] = load ptr addrspace(200), ptr [[RES2]], align 16
// HYBRID-LIBCALLS-NEXT:    [[TMP10:%.*]] = cmpxchg ptr [[TMP7]], ptr addrspace(200) [[TMP8]], ptr addrspace(200) [[TMP9]] seq_cst seq_cst, align 16
// HYBRID-LIBCALLS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP10]], 0
// HYBRID-LIBCALLS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP10]], 1
// HYBRID-LIBCALLS-NEXT:    br i1 [[TMP12]], label [[CMPXCHG_CONTINUE:%.*]], label [[CMPXCHG_STORE_EXPECTED:%.*]]
// HYBRID-LIBCALLS:       cmpxchg.store_expected:
// HYBRID-LIBCALLS-NEXT:    store ptr addrspace(200) [[TMP11]], ptr [[RES]], align 16
// HYBRID-LIBCALLS-NEXT:    br label [[CMPXCHG_CONTINUE]]
// HYBRID-LIBCALLS:       cmpxchg.continue:
// HYBRID-LIBCALLS-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP12]] to i8
// HYBRID-LIBCALLS-NEXT:    store i8 [[FROMBOOL]], ptr [[CMPXCHG_BOOL]], align 1
// HYBRID-LIBCALLS-NEXT:    [[TMP13:%.*]] = load i8, ptr [[CMPXCHG_BOOL]], align 1
// HYBRID-LIBCALLS-NEXT:    [[TOBOOL:%.*]] = trunc i8 [[TMP13]] to i1
// HYBRID-LIBCALLS-NEXT:    [[TMP14:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-LIBCALLS-NEXT:    store ptr addrspace(200) getelementptr (i8, ptr addrspace(200) null, i64 1), ptr [[DOTATOMICTMP]], align 16
// HYBRID-LIBCALLS-NEXT:    [[TMP15:%.*]] = load ptr addrspace(200), ptr [[DOTATOMICTMP]], align 16
// HYBRID-LIBCALLS-NEXT:    [[TMP16:%.*]] = atomicrmw add ptr [[TMP14]], ptr addrspace(200) [[TMP15]] seq_cst, align 16
// HYBRID-LIBCALLS-NEXT:    store ptr addrspace(200) [[TMP16]], ptr [[ATOMIC_TEMP]], align 16
// HYBRID-LIBCALLS-NEXT:    [[TMP17:%.*]] = load ptr addrspace(200), ptr [[ATOMIC_TEMP]], align 16
// HYBRID-LIBCALLS-NEXT:    ret void
//
// PURECAP-LIBCALLS-LABEL: define dso_local void @func3(
// PURECAP-LIBCALLS-SAME: ptr addrspace(200) noundef [[P:%.*]]) addrspace(200) #[[ATTR0]] {
// PURECAP-LIBCALLS-NEXT:  entry:
// PURECAP-LIBCALLS-NEXT:    [[P_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-LIBCALLS-NEXT:    [[RES:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-LIBCALLS-NEXT:    [[RES2:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-LIBCALLS-NEXT:    [[CMPXCHG_BOOL:%.*]] = alloca i8, align 1, addrspace(200)
// PURECAP-LIBCALLS-NEXT:    [[DOTATOMICTMP:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-LIBCALLS-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-LIBCALLS-NEXT:    store ptr addrspace(200) [[P]], ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP1:%.*]] = load atomic ptr addrspace(200), ptr addrspace(200) [[TMP0]] seq_cst, align 16
// PURECAP-LIBCALLS-NEXT:    store ptr addrspace(200) [[TMP1]], ptr addrspace(200) [[RES]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP2:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP3:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES]], align 16
// PURECAP-LIBCALLS-NEXT:    store atomic ptr addrspace(200) [[TMP3]], ptr addrspace(200) [[TMP2]] seq_cst, align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP4:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP5:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP6:%.*]] = atomicrmw xchg ptr addrspace(200) [[TMP4]], ptr addrspace(200) [[TMP5]] seq_cst, align 16
// PURECAP-LIBCALLS-NEXT:    store ptr addrspace(200) [[TMP6]], ptr addrspace(200) [[RES2]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP7:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP8:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP9:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[RES2]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP10:%.*]] = cmpxchg ptr addrspace(200) [[TMP7]], ptr addrspace(200) [[TMP8]], ptr addrspace(200) [[TMP9]] seq_cst seq_cst, align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP11:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP10]], 0
// PURECAP-LIBCALLS-NEXT:    [[TMP12:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP10]], 1
// PURECAP-LIBCALLS-NEXT:    br i1 [[TMP12]], label [[CMPXCHG_CONTINUE:%.*]], label [[CMPXCHG_STORE_EXPECTED:%.*]]
// PURECAP-LIBCALLS:       cmpxchg.store_expected:
// PURECAP-LIBCALLS-NEXT:    store ptr addrspace(200) [[TMP11]], ptr addrspace(200) [[RES]], align 16
// PURECAP-LIBCALLS-NEXT:    br label [[CMPXCHG_CONTINUE]]
// PURECAP-LIBCALLS:       cmpxchg.continue:
// PURECAP-LIBCALLS-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP12]] to i8
// PURECAP-LIBCALLS-NEXT:    store i8 [[FROMBOOL]], ptr addrspace(200) [[CMPXCHG_BOOL]], align 1
// PURECAP-LIBCALLS-NEXT:    [[TMP13:%.*]] = load i8, ptr addrspace(200) [[CMPXCHG_BOOL]], align 1
// PURECAP-LIBCALLS-NEXT:    [[TOBOOL:%.*]] = trunc i8 [[TMP13]] to i1
// PURECAP-LIBCALLS-NEXT:    [[TMP14:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-LIBCALLS-NEXT:    store ptr addrspace(200) getelementptr (i8, ptr addrspace(200) null, i64 1), ptr addrspace(200) [[DOTATOMICTMP]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP15:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[DOTATOMICTMP]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP16:%.*]] = atomicrmw add ptr addrspace(200) [[TMP14]], ptr addrspace(200) [[TMP15]] seq_cst, align 16
// PURECAP-LIBCALLS-NEXT:    store ptr addrspace(200) [[TMP16]], ptr addrspace(200) [[ATOMIC_TEMP]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP17:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[ATOMIC_TEMP]], align 16
// PURECAP-LIBCALLS-NEXT:    ret void
//
void func3(__uintcap_t *p) {


  __uintcap_t res;
  __uintcap_t res2;
  __atomic_load(p, &res, __ATOMIC_SEQ_CST); // libcalls-warning{{large atomic operation may incur significant performance penalty}}
  __atomic_store(p, &res, __ATOMIC_SEQ_CST); // libcalls-warning{{large atomic operation may incur significant performance penalty}}
  __atomic_exchange(p, &res, &res2, __ATOMIC_SEQ_CST); // libcalls-warning{{large atomic operation may incur significant performance penalty}}
  __atomic_compare_exchange(p, &res, &res2, 0, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST); // libcalls-warning{{large atomic operation may incur significant performance penalty}}
  __atomic_fetch_add(p, 1, __ATOMIC_SEQ_CST); // libcalls-warning{{large atomic operation may incur significant performance penalty}}
}

// HYBRID-LABEL: define dso_local void @func4(
// HYBRID-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// HYBRID-NEXT:    [[RES:%.*]] = alloca i64, align 8
// HYBRID-NEXT:    [[RES2:%.*]] = alloca i64, align 8
// HYBRID-NEXT:    [[CMPXCHG_BOOL:%.*]] = alloca i8, align 1
// HYBRID-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// HYBRID-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-NEXT:    [[TMP1:%.*]] = load atomic i64, ptr [[TMP0]] seq_cst, align 8
// HYBRID-NEXT:    store i64 [[TMP1]], ptr [[RES]], align 8
// HYBRID-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-NEXT:    [[TMP3:%.*]] = load i64, ptr [[RES]], align 8
// HYBRID-NEXT:    store atomic i64 [[TMP3]], ptr [[TMP2]] seq_cst, align 8
// HYBRID-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-NEXT:    [[TMP5:%.*]] = load i64, ptr [[RES]], align 8
// HYBRID-NEXT:    [[TMP6:%.*]] = atomicrmw xchg ptr [[TMP4]], i64 [[TMP5]] seq_cst, align 8
// HYBRID-NEXT:    store i64 [[TMP6]], ptr [[RES2]], align 8
// HYBRID-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-NEXT:    [[TMP8:%.*]] = load i64, ptr [[RES]], align 8
// HYBRID-NEXT:    [[TMP9:%.*]] = load i64, ptr [[RES2]], align 8
// HYBRID-NEXT:    [[TMP10:%.*]] = cmpxchg ptr [[TMP7]], i64 [[TMP8]], i64 [[TMP9]] seq_cst seq_cst, align 8
// HYBRID-NEXT:    [[TMP11:%.*]] = extractvalue { i64, i1 } [[TMP10]], 0
// HYBRID-NEXT:    [[TMP12:%.*]] = extractvalue { i64, i1 } [[TMP10]], 1
// HYBRID-NEXT:    br i1 [[TMP12]], label [[CMPXCHG_CONTINUE:%.*]], label [[CMPXCHG_STORE_EXPECTED:%.*]]
// HYBRID:       cmpxchg.store_expected:
// HYBRID-NEXT:    store i64 [[TMP11]], ptr [[RES]], align 8
// HYBRID-NEXT:    br label [[CMPXCHG_CONTINUE]]
// HYBRID:       cmpxchg.continue:
// HYBRID-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP12]] to i8
// HYBRID-NEXT:    store i8 [[FROMBOOL]], ptr [[CMPXCHG_BOOL]], align 1
// HYBRID-NEXT:    [[TMP13:%.*]] = load i8, ptr [[CMPXCHG_BOOL]], align 1
// HYBRID-NEXT:    [[TOBOOL:%.*]] = trunc i8 [[TMP13]] to i1
// HYBRID-NEXT:    ret void
//
// PURECAP-LABEL: define dso_local void @func4(
// PURECAP-SAME: ptr addrspace(200) noundef [[P:%.*]]) addrspace(200) #[[ATTR0]] {
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[P_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-NEXT:    [[RES:%.*]] = alloca i64, align 8, addrspace(200)
// PURECAP-NEXT:    [[RES2:%.*]] = alloca i64, align 8, addrspace(200)
// PURECAP-NEXT:    [[CMPXCHG_BOOL:%.*]] = alloca i8, align 1, addrspace(200)
// PURECAP-NEXT:    store ptr addrspace(200) [[P]], ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-NEXT:    [[TMP1:%.*]] = load atomic i64, ptr addrspace(200) [[TMP0]] seq_cst, align 8
// PURECAP-NEXT:    store i64 [[TMP1]], ptr addrspace(200) [[RES]], align 8
// PURECAP-NEXT:    [[TMP2:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-NEXT:    [[TMP3:%.*]] = load i64, ptr addrspace(200) [[RES]], align 8
// PURECAP-NEXT:    store atomic i64 [[TMP3]], ptr addrspace(200) [[TMP2]] seq_cst, align 8
// PURECAP-NEXT:    [[TMP4:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-NEXT:    [[TMP5:%.*]] = load i64, ptr addrspace(200) [[RES]], align 8
// PURECAP-NEXT:    [[TMP6:%.*]] = atomicrmw xchg ptr addrspace(200) [[TMP4]], i64 [[TMP5]] seq_cst, align 8
// PURECAP-NEXT:    store i64 [[TMP6]], ptr addrspace(200) [[RES2]], align 8
// PURECAP-NEXT:    [[TMP7:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-NEXT:    [[TMP8:%.*]] = load i64, ptr addrspace(200) [[RES]], align 8
// PURECAP-NEXT:    [[TMP9:%.*]] = load i64, ptr addrspace(200) [[RES2]], align 8
// PURECAP-NEXT:    [[TMP10:%.*]] = cmpxchg ptr addrspace(200) [[TMP7]], i64 [[TMP8]], i64 [[TMP9]] seq_cst seq_cst, align 8
// PURECAP-NEXT:    [[TMP11:%.*]] = extractvalue { i64, i1 } [[TMP10]], 0
// PURECAP-NEXT:    [[TMP12:%.*]] = extractvalue { i64, i1 } [[TMP10]], 1
// PURECAP-NEXT:    br i1 [[TMP12]], label [[CMPXCHG_CONTINUE:%.*]], label [[CMPXCHG_STORE_EXPECTED:%.*]]
// PURECAP:       cmpxchg.store_expected:
// PURECAP-NEXT:    store i64 [[TMP11]], ptr addrspace(200) [[RES]], align 8
// PURECAP-NEXT:    br label [[CMPXCHG_CONTINUE]]
// PURECAP:       cmpxchg.continue:
// PURECAP-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP12]] to i8
// PURECAP-NEXT:    store i8 [[FROMBOOL]], ptr addrspace(200) [[CMPXCHG_BOOL]], align 1
// PURECAP-NEXT:    [[TMP13:%.*]] = load i8, ptr addrspace(200) [[CMPXCHG_BOOL]], align 1
// PURECAP-NEXT:    [[TOBOOL:%.*]] = trunc i8 [[TMP13]] to i1
// PURECAP-NEXT:    ret void
//
// HYBRID-LIBCALLS-LABEL: define dso_local void @func4(
// HYBRID-LIBCALLS-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// HYBRID-LIBCALLS-NEXT:  entry:
// HYBRID-LIBCALLS-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// HYBRID-LIBCALLS-NEXT:    [[RES:%.*]] = alloca i64, align 8
// HYBRID-LIBCALLS-NEXT:    [[RES2:%.*]] = alloca i64, align 8
// HYBRID-LIBCALLS-NEXT:    [[CMPXCHG_BOOL:%.*]] = alloca i8, align 1
// HYBRID-LIBCALLS-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP1:%.*]] = load atomic i64, ptr [[TMP0]] seq_cst, align 8
// HYBRID-LIBCALLS-NEXT:    store i64 [[TMP1]], ptr [[RES]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP3:%.*]] = load i64, ptr [[RES]], align 8
// HYBRID-LIBCALLS-NEXT:    store atomic i64 [[TMP3]], ptr [[TMP2]] seq_cst, align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP5:%.*]] = load i64, ptr [[RES]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP6:%.*]] = atomicrmw xchg ptr [[TMP4]], i64 [[TMP5]] seq_cst, align 8
// HYBRID-LIBCALLS-NEXT:    store i64 [[TMP6]], ptr [[RES2]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP8:%.*]] = load i64, ptr [[RES]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP9:%.*]] = load i64, ptr [[RES2]], align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP10:%.*]] = cmpxchg ptr [[TMP7]], i64 [[TMP8]], i64 [[TMP9]] seq_cst seq_cst, align 8
// HYBRID-LIBCALLS-NEXT:    [[TMP11:%.*]] = extractvalue { i64, i1 } [[TMP10]], 0
// HYBRID-LIBCALLS-NEXT:    [[TMP12:%.*]] = extractvalue { i64, i1 } [[TMP10]], 1
// HYBRID-LIBCALLS-NEXT:    br i1 [[TMP12]], label [[CMPXCHG_CONTINUE:%.*]], label [[CMPXCHG_STORE_EXPECTED:%.*]]
// HYBRID-LIBCALLS:       cmpxchg.store_expected:
// HYBRID-LIBCALLS-NEXT:    store i64 [[TMP11]], ptr [[RES]], align 8
// HYBRID-LIBCALLS-NEXT:    br label [[CMPXCHG_CONTINUE]]
// HYBRID-LIBCALLS:       cmpxchg.continue:
// HYBRID-LIBCALLS-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP12]] to i8
// HYBRID-LIBCALLS-NEXT:    store i8 [[FROMBOOL]], ptr [[CMPXCHG_BOOL]], align 1
// HYBRID-LIBCALLS-NEXT:    [[TMP13:%.*]] = load i8, ptr [[CMPXCHG_BOOL]], align 1
// HYBRID-LIBCALLS-NEXT:    [[TOBOOL:%.*]] = trunc i8 [[TMP13]] to i1
// HYBRID-LIBCALLS-NEXT:    ret void
//
// PURECAP-LIBCALLS-LABEL: define dso_local void @func4(
// PURECAP-LIBCALLS-SAME: ptr addrspace(200) noundef [[P:%.*]]) addrspace(200) #[[ATTR0]] {
// PURECAP-LIBCALLS-NEXT:  entry:
// PURECAP-LIBCALLS-NEXT:    [[P_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-LIBCALLS-NEXT:    [[RES:%.*]] = alloca i64, align 8, addrspace(200)
// PURECAP-LIBCALLS-NEXT:    [[RES2:%.*]] = alloca i64, align 8, addrspace(200)
// PURECAP-LIBCALLS-NEXT:    [[CMPXCHG_BOOL:%.*]] = alloca i8, align 1, addrspace(200)
// PURECAP-LIBCALLS-NEXT:    store ptr addrspace(200) [[P]], ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP1:%.*]] = load atomic i64, ptr addrspace(200) [[TMP0]] seq_cst, align 8
// PURECAP-LIBCALLS-NEXT:    store i64 [[TMP1]], ptr addrspace(200) [[RES]], align 8
// PURECAP-LIBCALLS-NEXT:    [[TMP2:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP3:%.*]] = load i64, ptr addrspace(200) [[RES]], align 8
// PURECAP-LIBCALLS-NEXT:    store atomic i64 [[TMP3]], ptr addrspace(200) [[TMP2]] seq_cst, align 8
// PURECAP-LIBCALLS-NEXT:    [[TMP4:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP5:%.*]] = load i64, ptr addrspace(200) [[RES]], align 8
// PURECAP-LIBCALLS-NEXT:    [[TMP6:%.*]] = atomicrmw xchg ptr addrspace(200) [[TMP4]], i64 [[TMP5]] seq_cst, align 8
// PURECAP-LIBCALLS-NEXT:    store i64 [[TMP6]], ptr addrspace(200) [[RES2]], align 8
// PURECAP-LIBCALLS-NEXT:    [[TMP7:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[P_ADDR]], align 16
// PURECAP-LIBCALLS-NEXT:    [[TMP8:%.*]] = load i64, ptr addrspace(200) [[RES]], align 8
// PURECAP-LIBCALLS-NEXT:    [[TMP9:%.*]] = load i64, ptr addrspace(200) [[RES2]], align 8
// PURECAP-LIBCALLS-NEXT:    [[TMP10:%.*]] = cmpxchg ptr addrspace(200) [[TMP7]], i64 [[TMP8]], i64 [[TMP9]] seq_cst seq_cst, align 8
// PURECAP-LIBCALLS-NEXT:    [[TMP11:%.*]] = extractvalue { i64, i1 } [[TMP10]], 0
// PURECAP-LIBCALLS-NEXT:    [[TMP12:%.*]] = extractvalue { i64, i1 } [[TMP10]], 1
// PURECAP-LIBCALLS-NEXT:    br i1 [[TMP12]], label [[CMPXCHG_CONTINUE:%.*]], label [[CMPXCHG_STORE_EXPECTED:%.*]]
// PURECAP-LIBCALLS:       cmpxchg.store_expected:
// PURECAP-LIBCALLS-NEXT:    store i64 [[TMP11]], ptr addrspace(200) [[RES]], align 8
// PURECAP-LIBCALLS-NEXT:    br label [[CMPXCHG_CONTINUE]]
// PURECAP-LIBCALLS:       cmpxchg.continue:
// PURECAP-LIBCALLS-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP12]] to i8
// PURECAP-LIBCALLS-NEXT:    store i8 [[FROMBOOL]], ptr addrspace(200) [[CMPXCHG_BOOL]], align 1
// PURECAP-LIBCALLS-NEXT:    [[TMP13:%.*]] = load i8, ptr addrspace(200) [[CMPXCHG_BOOL]], align 1
// PURECAP-LIBCALLS-NEXT:    [[TOBOOL:%.*]] = trunc i8 [[TMP13]] to i1
// PURECAP-LIBCALLS-NEXT:    ret void
//
void func4(long *p) {


  long res;
  long res2;
  __atomic_load(p, &res, __ATOMIC_SEQ_CST); // libcalls-warning{{large atomic operation may incur significant performance penalty}}
  __atomic_store(p, &res, __ATOMIC_SEQ_CST); // libcalls-warning{{large atomic operation may incur significant performance penalty}}
  __atomic_exchange(p, &res, &res2, __ATOMIC_SEQ_CST); // libcalls-warning{{large atomic operation may incur significant performance penalty}}
  __atomic_compare_exchange(p, &res, &res2, 0, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST); // libcalls-warning{{large atomic operation may incur significant performance penalty}}
}
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK: {{.*}}
